package com.HydroPonics.entity;

public enum CustomerServices {
	NFT_BASED_HYDROPONICS, DUTCH_BASED_HYDROPONICS, COCOPEAT_BASED_HYDROPONICS, CUSTOMIZED_HIGHTECH_TRIPLE_LAYER_WIRE_ROPE_NETHOUSE_ISRAEL;
}
